### ISSUE TITLE
Réecrire les resolvers et services de l'API

### ISSUE THREAD

**Issue by AlaricRG** [SOS-Tag/sos-tag-api#11]

**Comment by AlaricRG** [comment]
- [ ] updateSheet(id, {...medicalDataToUpdate} )
   - [ ] vérifier que la sheet est bien liée à l'utilisateur
 - [ ] deleteSheet(id)
   - [ ] penser à supprimer la référence dans Account
 - [ ] createSheet(default {} || {...medicalData})
   - [ ] si utilisateur authentifié dans la requête
 - [ ] linkSheet(userId, sheetId)
   - sert pour lier les fiches pré-générées à un utilisateur
 - [ ] getAuthenticatedAccount()
 - [ ] repasser sur les resolvers existants (user, authentification ...)
 - [ ] disableSheet(id)

**Comment by ludchieng** [comment]
* [x]  updateSheet(id, {...medicalDataToUpdate} )
  * [x]  vérifier que la sheet est bien liée à l'utilisateur
* [x]  deleteSheet(id)
  * [x]  penser à supprimer la référence dans Account → pas besoin car pas de référence dans User
* [x]  createSheet(default {} || {...medicalData}) → seulement par l'administrateur
  * [x]  si utilisateur authentifié dans la requête → seulement par l'admin
* [x]  linkSheet(userId, sheetId) → assignSheetToUser()
  * sert pour lier les fiches pré-générées à un utilisateur → OK
* [x]  getAuthenticatedAccount() → currentUser()
* [x]  repasser sur les resolvers existants (user, authentification ...)
* [x]  disableSheet(id) → updateSheet({ activated: false})
