### ISSUE TITLE
Changer format des id de User

### ISSUE THREAD

**Issue by AlaricRG** [SOS-Tag/sos-tag-api#6]
Pour l'instant ils sont bien trop long, on vise des id de 8 charactères

**Comment by N0Ls** [comment]
Tu confonds les id des utilisateurs et ceux des QR code non ? 
C'est les id des QR code qui sont de 8 caractères.

**Comment by AlaricRG** [comment]
@N0Ls mais on fait une différence entre les 2 au final ? C'est pas super clair pour moi
